from langchain.chat_models import ChatOpenAI
from langchain.chains import create_extraction_chain, create_extraction_chain_pydantic
from langchain.prompts import ChatPromptTemplate
from langchain.callbacks import get_openai_callback
from langchain.chat_models import AzureChatOpenAI

from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional
from dotenv import load_dotenv

class Company_details(BaseModel):
    company_name: str = Field(..., description="Only company names not city or country name.")
    money_invested: Optional[int] = Field(...,description="describes the amount of money invested by the company in million.")
    growth_figures: Optional[str] = Field(..., description="how much the company has grown.")
    Year: Optional[str] =  Field(..., description="Year in which company has invested money or started business.")


schema = {
    "properties": {
        "company_name": {"type": "string"},
        "money_invested": {"type": "string"},
        "growth_figures": {"type": "string"},
        "Year": {"type": "string"},
    },
    "required": ["company_name", "money_invested"],
}

load_dotenv()

tc_01 = """ In a city where dreams have weaved their enchanting tapestry, a remarkable metamorphosis has taken place. Mumbai, the illustrious city of dreams, has now earned itself a new epithet — the city of data centres.

Today, this pulsating metropolis stands tall, as an emerging powerhouse that proudly houses a burgeoning cluster of data centres — a force to be reckoned with, ranking third across the entire Asia-Pacific (APAC) region.

India's data-driven revolution is about to launch realty asset investments sky-high, while Mumbai's data centres dominate the scene like data dynamos. Accounting for 49% of the functional area and 48% of the IT supply, Mumbai is the data centre hub to watch out for. The capacity is a formidable 270 megawatt (MW) but hold your breath — there's a mind-blowing 1,272 MW in the pipeline.

According to Avendus Capital, India's data centres are the trailblazers of realty asset investments and are set to grow at an impressive 40% CAGR. By 2025, the data centres will reach a staggering 1,700 MW capacity, backed by estimated investment worth USD5 billion.

And the government? Well, it has thrown its might behind this digital revolution. In the budget for fiscal 2022, multiple initiatives were unveiled with a singular objective: to establish India as a shining beacon of data centre supremacy. On the ground
In the heart of Andheri, a data centre, Symphony Fintech, modestly stands, concealing within its walls a world of intrigue and operations that ET Prime sought to uncover. Just a stone's throw away from the airport, this unassuming hub serves as a sanctuary for high-frequency traders (HFT), brokers, and an array of entities vying for their share of digital dominance.

As ET Prime ventured into the depths of Symphony's server rooms, a theatrical display unfolded before their eyes. Cables of vibrant hues danced along the ceiling, resembling a technicolour serpent, while the frigid embrace of liquid nitrogen held the atmosphere in icy suspense. In this mesmerising tableau, a multitude of questions swirled like the digital currents that flowed through the room.

Our curiosity first alighted upon the origins of data centres within the city's embrace.

According to an official at Symphony Fintech, 2014 proved to be the epoch that forever shaped the data centre realm. The tides of change and shifting interests “surged forth in 2014 and has continued through 2020, with many brokers transitioning in and out of high-frequency trading while simultaneously entering algorithmic trading," shared the official.

He further disclosed the remarkable transformation of this landscape, with initially only about 100 brokers competing for dominance armed with the advantage of a single data server. Today, the data centre is a ‘fierce battleground’ boasting over 500 brokers.

Yet, the race to consume data transcends the boundaries of the financial realm.

Prashant Thakur, senior director and head - Research, ANAROCK Group, elucidated the key transformations that have fuelled the demand for data centres in India since 2014. These transformations include the advent of affordable mobile tariffs, spearheading an era of widespread mobile penetration; the wave of demonetisation and the government's relentless pursuit of digital transactions and technological progress; and the enforcement of data localisation laws, mandating the storage of Indian-generated data within the country's borders.

Notably, the revenue generated by the data centre industry paints a picture of staggering growth. According to an ANAROCK report, the industry's revenue surged from a humble USD385 million in 2014 to USD1.2 billion in 2021, indicating an annual growth rate of 10% over the past two years. The industry's improved operational efficiencies and economies of scale are further underscored by a significant rise in Ebitda margin, soaring from 24% in 2019 to a remarkable 33% in 2021.

As per Statista Market Research, India’s revenue in the data centre market is projected to reach USD7.83 billion in 2023. """


# llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613")
llm = AzureChatOpenAI(
    deployment_name="chat",
    model_name="gpt-35-turbo",
)


# chain = create_extraction_chain(schema, llm)

# response = chain.run(tc_01)
# print(response)


pydantic_chain = create_extraction_chain_pydantic(Company_details, llm)
res_obj = pydantic_chain.run(tc_01)
# print(res_obj)

for index, item in enumerate(res_obj):
    print("------{} of {}".format(index+1, len(res_obj)))
    print(item)
    print("Type: {}".format(type(item)))
